# Environment
language: cpp
sudo: false
compiler:
  - gcc
#  - clang
env:
  - DEBUG=1
#  - DEBUG=0

cache:
  ccache: true

addons:
  apt:
    sources:
    packages:
      - libboost-all-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libcurl4-openssl-dev
      - libjemalloc-dev=3.*

# Install build dependencies
before_script:
  - ./configure --allow-fetch --ccache
  - ccache -z
  - make --jobs 3 support DEBUG=$DEBUG

# Build script
script:
  - make --jobs 3 test-deps DEBUG=$DEBUG
#  && test/run

after_script:
  - ccache -s

# notifications:
  # # Email commit author only on build status change
  # email:
    # on_success: change
    # on_failure: change

  # # Always ping a webhook when something is broken. The webhook looks
  # # only for builds in next, and notifies everyone on the dev team
  # # that next is broken. This isn't currently possible directly with
  # # Travis.
  # webhooks:
    # urls:
      # - https://zapier.com/hooks/catch/n/ux03n/
    # on_success: never
    # on_failure: always

