# Environment
language: cpp
sudo: false
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
    - DEBUG=1
  matrix:
    - TEST=unit
    - TEST=!unit

addons:
    apt:
      packages:
        # Packages list from documentation (2016/01/24)
        - libncurses5-dev
        - protobuf-compiler
        - libprotobuf-dev
        - libcurl4-openssl-dev
        - libboost-all-dev
        - libjemalloc-dev
  
cache:
  apt: true
  ccache: true
  directories:
    - ~/.npm
    - ~/npm-cache

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install stable
      npm install -g npm@2
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update >/dev/null
      brew uninstall node
      brew install node --without-npm
      echo prefix=~/.node >> ~/.npmrc
      curl -L https://www.npmjs.com/install.sh | sh
    fi
#      --without-npm;
#      echo prefix=~/.node >> ~/.npmrc;
#      ( curl -L https://www.npmjs.com/install.sh | sh );
#      fi

# Install build dependencies
install:
  - ./configure --allow-fetch --ccache
  - make support DEBUG=$DEBUG -j 3

# Build script
script:
  - make test DEBUG=$DEBUG --jobs 3

#notifications:
  # Email commit author only on build status change
#  email:
#    on_success: change
#    on_failure: change

  # Always ping a webhook when something is broken. The webhook looks
  # only for builds in next, and notifies everyone on the dev team
  # that next is broken. This isn't currently possible directly with
  # Travis.
#  webhooks:
#    urls:
#      - https://zapier.com/hooks/catch/n/ux03n/
#    on_success: never
#    on_failure: always

