# Environment
language: cpp
#compiler:
#  - gcc
#  - clang
env:
#  - DEBUG=1
#  - DEBUG=0
  
cache:
  apt: true
  ccache: true
  directories:
    - ~/.npm
    - ~/npm-cache

addons:
  apt:
#    sources:
#      - boost-latest
    packages:
      - libncurses5-dev
#      - protobuf-compiler
#      - libprotobuf-dev
#      - libcurl4-openssl-dev
#      - libboost1.54-all-dev
#      - libjemalloc-dev

matrix:
  include:
    - os: linux
      sudo: false
      compiler: gcc
      env: DEBUG=1
      # Packages list from documentation (2016/01/24)
      addons:
        apt:
          packages:
            - libncurses5-dev
            - protobuf-compiler
            - libprotobuf-dev
            - libcurl4-openssl-dev
            - libboost-all-dev
            - libjemalloc-dev
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: DEBUG=1
      # Packages list from documentation (2016/01/24)
      addons:
        apt:
          packages:
            - libncurses5-dev
            - protobuf-compiler
            - libprotobuf-dev
            - libcurl4-openssl-dev
            - libboost-all-dev
            - libjemalloc-dev
    - os: linux
      sudo: false
      compiler: gcc
      env: DEBUG=1
      # Minimalist packages list
      addons:
        apt:
          packages:
            - libncurses5-dev
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: DEBUG=1
      # Minimalist packages list
      addons:
        apt:
          packages:
            - libncurses5-dev
    - os: osx

before_install:
  - nvm install stable
#  - npm install -g npm@2

# Install build dependencies
install:
  - ./configure --allow-fetch --ccache
  - make support DEBUG=$DEBUG -j 3

# Build script
script:
  - make test-deps DEBUG=$DEBUG -j 3 && ./test/run --jobs 3

#notifications:
  # Email commit author only on build status change
#  email:
#    on_success: change
#    on_failure: change

  # Always ping a webhook when something is broken. The webhook looks
  # only for builds in next, and notifies everyone on the dev team
  # that next is broken. This isn't currently possible directly with
  # Travis.
#  webhooks:
#    urls:
#      - https://zapier.com/hooks/catch/n/ux03n/
#    on_success: never
#    on_failure: always

