sudo: false

# Environment
language: cpp
compiler:
  - gcc
  - clang
env:
  - DEBUG=1
  - DEBUG=0

cache:
  apt: true
  ccache: true
  directories:
    - ~/.npm
    - ~/npm-cache

addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotobuf-dev
      - libcurl4-openssl-dev
      - libboost-all-dev
      - libncurses5-dev
      - libjemalloc-dev

before_install:
  - nvm install stable
  - npm install -g npm@2

# Install build dependencies
install:
  - ./configure --allow-fetch --ccache

# Build script
script:
  - make -j 3 test-deps DEBUG=$DEBUG && ./test/run --jobs 3
#  --verbose
#  - make test TEST=travis RUN_TEST_ARGS='-j3 -w-' DEBUG=$DEBUG

#notifications:
  # Email commit author only on build status change
#  email:
#    on_success: change
#    on_failure: change

  # Always ping a webhook when something is broken. The webhook looks
  # only for builds in next, and notifies everyone on the dev team
  # that next is broken. This isn't currently possible directly with
  # Travis.
#  webhooks:
#    urls:
#      - https://zapier.com/hooks/catch/n/ux03n/
#    on_success: never
#    on_failure: always

