# Environment
language: cpp
sudo: required
compiler:
  - gcc
#  - clang
env:
  - DEBUG=1
#  - DEBUG=0

addons:
  apt:
    packages:
      nodejs=0.12.*
      libssl-dev
      protobuf-compiler
      libprotobuf-dev
      libcurl4-openssl-dev
      libjemalloc-dev

cache:
  directories:
    - $HOME/.ccache
    - external
    - ~/.npm

install:
#  - export PATH="/usr/lib/ccache:$PATH"
  # Node.js packages on Ubuntu renames 'node' to 'nodejs'
  - ln -s /usr/bin/nodejs /usr/bin/node
#  - mkdir ~/.intercept && ln -s /usr/bin/nodejs ~/.intercept/node && export PATH="~/.intercept:$PATH"
  - npm install -g coffee-script@1.10.0
  - npm install -g browserify@12.0.1
#  - npm install -g bluebird@2.9.32
  - ./configure --ccache
  - make support

script:
  - make DEBUG=$DEBUG && make test

# notifications:
  # # Email commit author only on build status change
  # email:
    # on_success: change
    # on_failure: change

  # # Always ping a webhook when something is broken. The webhook looks
  # # only for builds in next, and notifies everyone on the dev team
  # # that next is broken. This isn't currently possible directly with
  # # Travis.
  # webhooks:
    # urls:
      # - https://zapier.com/hooks/catch/n/ux03n/
    # on_success: never
    # on_failure: always

