# Environment
language: cpp
sudo: false
os:
  - linux
#  - osx
compiler:
  - g++
#  - clang
env:
  global:
    - DEBUG=1
  matrix:
    - TEST=unit
#    - TEST=!unit

# matrix:
  # include:
    # - os: linux
      # dist: trusty
      # sudo: required
      # compiler: g++
      # env:
      # - TEST=unit
    # - os: linux
      # dist: trusty
      # sudo: required
      # compiler: g++
      # env:
      # - TEST=!unit
    # - os: linux
      # dist: trusty
      # sudo: required
      # compiler: clang
      # env:
      # - TEST=unit
    # - os: linux
      # dist: trusty
      # sudo: required
      # compiler: clang
      # env:
      # - TEST=!unit

addons:
    apt:
      packages:
        # Packages list from documentation (2016/01/24)
        - libncurses5-dev
        - protobuf-compiler
        - libprotobuf-dev
        - libcurl4-openssl-dev
        - libboost-all-dev
        - libjemalloc-dev
  
cache:
  directories:
    - $HOME/.ccache
    - external
    - build/external
#    - precompiled

before_install:
  - |
    if [[ `nvm --version 2>/dev/null` == "" ]]; then
      # Install nvm
      git clone https://github.com/creationix/nvm.git ~/.nvm && pushd ~/.nvm && git checkout `git describe --abbrev=0 --tags` && popd
      . ~/.nvm/nvm.sh
    fi
    # Install latest stable Node.js
    nvm install node
    # Install latest version 2 of npm
    npm install -g npm@2

# Install build dependencies
install:
  - |
    if [[ `ccache --version 2>/dev/null` != "" ]]; then
      export CCACHE_SWITCH=--ccache
      ccache --version
    fi
  - ./configure --allow-fetch $CCACHE_SWITCH
  - make support DEBUG=$DEBUG --jobs 3

# Build script
script:
  - make test-deps DEBUG=$DEBUG --jobs 3
#  && make test

after_script:
  - |
    if [[ "$CCACHE_SWITCH" != "" ]]; then
      ccache --show-stats
    fi

before_cache:
  - rm -f build/external/*/install.witness build/external/*.log

#notifications:
  # Email commit author only on build status change
#  email:
#    on_success: change
#    on_failure: change

  # Always ping a webhook when something is broken. The webhook looks
  # only for builds in next, and notifies everyone on the dev team
  # that next is broken. This isn't currently possible directly with
  # Travis.
#  webhooks:
#    urls:
#      - https://zapier.com/hooks/catch/n/ux03n/
#    on_success: never
#    on_failure: always

