# Environment
language: cpp
sudo: required
os:
  - linux
compiler:
  - g++
#  - clang
env:
  - DEBUG=1
#  - DEBUG=0

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: g++
      env:
        - DEBUG=1

cache:
  directories:
    - $HOME/.ccache
    - external
    - ~/.npm

install:
  - sudo add-apt-repository https://deb.nodesource.com/node_0.12
  - curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  - sudo apt-get update
  - apt-cache search libv8
  - sudo apt-get install --assume-yes --no-install-recommends --quiet
      nodejs=0.12.*
      libboost-all-dev
      protobuf-compiler
      libprotobuf-dev
      libcurl4-openssl-dev
      libjemalloc-dev=3.*
  - sudo npm install -g coffee-script@1.10.0
  - sudo npm install -g browserify@12.0.1
#  - npm install -g bluebird@2.9.32
  - |
    if [[ `ccache --version 2>/dev/null` != "" ]]; then
      export CCACHE_SWITCH=--ccache
      ccache --version
    fi
  - ./configure $CCACHE_SWITCH
  - PATH="/usr/lib/ccache:$PATH" make support

script:
  - make DEBUG=$DEBUG && make test

after_script:
  - |
    if [[ "$CCACHE_SWITCH" != "" ]]; then
      ccache --show-stats
    fi

# notifications:
  # # Email commit author only on build status change
  # email:
    # on_success: change
    # on_failure: change

  # # Always ping a webhook when something is broken. The webhook looks
  # # only for builds in next, and notifies everyone on the dev team
  # # that next is broken. This isn't currently possible directly with
  # # Travis.
  # webhooks:
    # urls:
      # - https://zapier.com/hooks/catch/n/ux03n/
    # on_success: never
    # on_failure: always

