sudo: false

# Environment
language: cpp
compiler:
  - gcc
  - clang
env:
  - DEBUG=1
  - DEBUG=0

cache:
  apt: true
  ccache: true
  directories:
    - ~/.npm
    - ~/npm-cache

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - protobuf-compiler
      - libprotobuf-dev
      - libcurl4-openssl-dev
      - libboost-all-dev
      - libncurses5-dev
      - libjemalloc-dev

before_install:
  - nvm install stable
  - npm install -g npm@2

# Install build dependencies
install:
  # we need a custom ppa for latest boost libs (1.46, which is on
  # Travis, doesn't work with Clang and C++ 11)
#  - yes | sudo apt-add-repository ppa:jkeiren/ppa
#  - sudo apt-get update
#  - sudo apt-get install libboost1.48-all-dev

# Build script
script:
  - if [ "$DEBUG" = "1" ]; then export VERBOSE="--verbose"; fi
  - ./configure --allow-fetch --ccache && make -j 3 test-deps DEBUG=$DEBUG && ./test/run --jobs 3 $VERBOSE
#  - make test TEST=travis RUN_TEST_ARGS='-j3 -w-' DEBUG=$DEBUG

#notifications:
  # Email commit author only on build status change
#  email:
#    on_success: change
#    on_failure: change

  # Always ping a webhook when something is broken. The webhook looks
  # only for builds in next, and notifies everyone on the dev team
  # that next is broken. This isn't currently possible directly with
  # Travis.
#  webhooks:
#    urls:
#      - https://zapier.com/hooks/catch/n/ux03n/
#    on_success: never
#    on_failure: always

